"""add image_file_path in People table

Revision ID: a8ac964e6b45
Revises: ce83294b5572
Create Date: 2025-06-24 13:37:23.663452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8ac964e6b45'
down_revision: Union[str, None] = 'ce83294b5572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'image_path')
    # ### end Alembic commands ###
