"""Change date_of_birth from DateTime to Date in Person table

Revision ID: aa8c35ad676a
Revises: a8ac964e6b45
Create Date: 2025-06-24 14:01:08.187105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa8c35ad676a'
down_revision: Union[str, None] = 'a8ac964e6b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'people',
        'date_of_birth',
        existing_type=postgresql.TIMESTAMP(timezone=True), # Or sa.DateTime(timezone=True)
        type_=sa.Date(),
        existing_nullable=True,
        # If you had a default, you might need existing_server_default
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'people',
        'date_of_birth',
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True), # Or sa.DateTime(timezone=True)
        existing_nullable=True,
        # If you had a default, you might need existing_server_default
    )
    # ### end Alembic commands ###
